/**
 * @agentfare/proxy — Admin API (loopback-only).
 *
 * JSON endpoints the GUI (and any local tooling) use to inspect cost data, logs,
 * the model registry, the provider map, and — since the cc-switch rework — to
 * read/switch the active model lock at runtime.
 *
 * Security: read endpoints carry no auth of their own; the HTTP layer in
 * server.ts gates the whole /api branch on a loopback remote address as
 * defense-in-depth. Write endpoints (POST /api/active) additionally require an
 * admin token (x-agentfare-admin-token header) generated by the daemon at
 * startup and persisted to proxy.json — the token scheme this file originally
 * reserved. The token bootstrap (GET /api/admin-token) and the write endpoint
 * are further origin-gated (isAllowedAdminOrigin): a same-machine web page has
 * a loopback source IP, so loopback alone can't stop it — browsers always
 * send Origin, which must be the Tauri webview or vite dev origin (or absent
 * for curl/SDK). This is not a multi-user boundary (any process that can read
 * keys.json can already impersonate the user), but it satisfies the explicit
 * "do not add write endpoints without a token scheme" contract and guards
 * against accidental/drive-by POSTs and same-machine web-origin attacks.
 */

import * as crypto from "node:crypto";
import type { TrackingDatabase, RoutingConfig, ProviderConfig } from "@agentfare/core";
import type { ModelRegistry } from "@agentfare/models";
import type { ProviderInfo } from "./provider-map.js";

/** cc-switch 手动锁定请求/响应体。 */
export interface ActiveLock {
  lockMode: "auto" | "model" | "provider";
  activeModel?: string;
  activeProvider?: string;
}

export interface AdminDeps {
  db?: TrackingDatabase;
  registry?: ModelRegistry;
  providerMap?: Record<string, ProviderInfo>;
  /** 当前 routing 配置（GET /api/active 读锁定状态）。 */
  getRouting?: () => RoutingConfig;
  /**
   * 应用手动锁定并热加载配置（POST /api/active）。daemon 端实现：写
   * config.json 的 routing.lockMode/activeModel/activeProvider → 重建
   * RequestHandler/ModelRegistry/providerMap，使下一个请求即按新锁定路由。
   */
  applyLock?: (lock: ActiveLock) => { ok: true } | { ok: false; error: string };
  /**
   * 持久化 API key 到 keys.json（POST /api/keys）。daemon 端实现：调
   * credential-store.saveKeys（合并写 + 权限加固 + 失效缓存），下一个请求
   * 即按新 key 转发，无需 reload config。
   */
  saveKeys?: (updates: Record<string, string>) => void;
  /**
   * 合并 provider 配置进 config.json 并热加载（POST /api/providers）。daemon
   * 端实现：buildProvidersConfigJson patch → 写盘 → reloadConfig 重建
   * providerMap，下一个请求即按新 provider 配置路由。
   */
  applyProviders?: (
    update: Record<string, ProviderConfig>,
  ) => { ok: true } | { ok: false; error: string };
  /** admin 写端点鉴权 token；未配置则写端点拒绝（501 admin_disabled）。 */
  adminToken?: string;
}

export interface AdminResponse {
  status: number;
  body: unknown;
}

const RANGE_RE = /^(\d+)([dhm])$/;
const DEFAULT_LOG_LIMIT = 100;
const MAX_LOG_LIMIT = 1000;
const VALID_LOCK_MODES: ReadonlySet<string> = new Set(["auto", "model", "provider"]);

/**
 * Parse a time range (e.g. "7d", "24h", "30m"). Invalid input is ignored
 * (treated as "all-time") rather than rejected — the GUI may forward
 * user-typed values, and the read path fails soft.
 */
function parseRange(range: string | undefined): string | undefined {
  if (!range) return undefined;
  return RANGE_RE.test(range) ? range : undefined;
}

function parseLimit(raw: string | undefined): number {
  const n = parseInt(raw ?? "", 10);
  if (!Number.isFinite(n) || n <= 0) return DEFAULT_LOG_LIMIT;
  return Math.min(n, MAX_LOG_LIMIT);
}

/**
 * Constant-time admin-token check. Both sides are SHA-256 hashed to a fixed
 * length before timingSafeEqual, so a length mismatch no longer
 * short-circuits — short-circuiting on length would leak len(expected) as a
 * timing oracle if tokens were ever variable-length (today's randomUUID is a
 * fixed 36 chars, but the hash makes the constant-time contract hold
 * regardless). Returns false if either side is missing.
 */
function adminTokenOk(provided: string | undefined, expected: string | undefined): boolean {
  if (!expected || !provided) return false;
  const a = crypto.createHash("sha256").update(provided).digest();
  const b = crypto.createHash("sha256").update(expected).digest();
  return crypto.timingSafeEqual(a, b);
}

/**
 * Origins allowed to read the admin token / call the write endpoint. The GUI
 * ships as a Tauri webview (`tauri://localhost` on macOS/Linux,
 * `http://tauri.localhost` on Windows WebView2); vite dev runs on
 * `http://localhost:5173` (and `http://127.0.0.1:5173`). A loopback remote
 * address alone is NOT sufficient: any web page the user opens in a browser
 * on the same machine also has a loopback source IP, so without an origin
 * gate a malicious site could GET /api/admin-token (a simple request — no
 * preflight, and an echoing ACAO would let its JS read the response) then
 * POST /api/active to silently re-route all the user's LLM traffic.
 */
const ADMIN_ALLOWED_ORIGINS: ReadonlySet<string> = new Set([
  "tauri://localhost",
  "http://tauri.localhost",
  "http://localhost:5173",
  "http://127.0.0.1:5173",
]);

/**
 * Whether a request's Origin may read the admin token / call the write
 * endpoint. An absent Origin (curl/SDK) is allowed — those callers are
 * already gated by the loopback check + token; this check exists solely to
 * stop a web page (which always sends Origin on cross-site fetches) from
 * bootstrapping the token.
 */
export function isAllowedAdminOrigin(origin: string | undefined): boolean {
  if (!origin) return true;
  return ADMIN_ALLOWED_ORIGINS.has(origin);
}

/**
 * Whether a request's remote address is loopback (127.0.0.0/8 or ::1, incl.
 * IPv4-mapped ::ffff:127.x.x.x). Admin endpoints are loopback-only.
 */
export function isLoopback(addr: string | undefined): boolean {
  if (!addr) return false;
  if (addr === "::1") return true;
  if (addr.startsWith("::ffff:")) {
    const v4 = addr.slice(7);
    return v4.startsWith("127.");
  }
  return /^127\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(addr);
}

/**
 * Dispatch a /api/* admin request. Returns null when the path is not under
 * /api, so the caller can fall through to normal proxy routing.
 */
export function handleAdminRequest(
  method: string,
  pathname: string,
  query: Record<string, string | undefined>,
  headers: Record<string, string | undefined>,
  body: string | undefined,
  deps: AdminDeps,
): AdminResponse | null {
  if (!pathname.startsWith("/api")) return null;

  // Write endpoints (POST, token-gated). Origin is checked before the token so
  // a non-allowlisted web page never learns whether its token guess was right.
  // cc-switch 模式扩展：active/keys/providers 三个写端点共用 origin 门控 +
  // token 鉴权（GUI 一等公民 A2/A3，让纯 GUI 用户无需 CLI 即可填 key、配
  // provider）。
  if (method === "POST") {
    if (!isAllowedAdminOrigin(headers["origin"])) {
      return { status: 403, body: { error: "forbidden_origin" } };
    }
    if (pathname === "/api/active") return handleSetActive(headers, body, deps);
    if (pathname === "/api/keys") return handleSetKeys(headers, body, deps);
    if (pathname === "/api/providers") return handleSetProviders(headers, body, deps);
  }

  // All other admin endpoints are read-only GET
  if (method !== "GET") return { status: 405, body: { error: "method_not_allowed" } };

  switch (pathname) {
    case "/api/cost": {
      if (!deps.db) return { status: 503, body: { error: "db_unavailable" } };
      const range = parseRange(query.range);
      return {
        status: 200,
        body: {
          summary: deps.db.getCostSummary(range),
          byStep: deps.db.getStepSummary(range),
          byTool: deps.db.getToolSummary(range),
        },
      };
    }
    case "/api/logs": {
      if (!deps.db) return { status: 503, body: { error: "db_unavailable" } };
      const limit = parseLimit(query.limit);
      const logs = deps.db.queryLogs({}, limit);
      return { status: 200, body: { logs } };
    }
    case "/api/models": {
      if (!deps.registry) return { status: 503, body: { error: "registry_unavailable" } };
      const models = deps.registry.getAll().map((m) => ({
        id: m.id,
        provider: m.provider,
        tier: m.tier,
        pricing: {
          inputPerMillion: m.pricing.inputPerMillion,
          outputPerMillion: m.pricing.outputPerMillion,
        },
      }));
      return { status: 200, body: { models } };
    }
    case "/api/scores": {
      if (!deps.db) return { status: 503, body: { error: "db_unavailable" } };
      return { status: 200, body: { scores: deps.db.loadAllModelScores() } };
    }
    case "/api/providers": {
      return { status: 200, body: { providers: deps.providerMap ?? {} } };
    }
    case "/api/active": {
      const routing = deps.getRouting?.();
      return {
        status: 200,
        body: {
          lockMode: routing?.lockMode ?? "auto",
          activeModel: routing?.activeModel ?? null,
          activeProvider: routing?.activeProvider ?? null,
        },
      };
    }
    case "/api/admin-token": {
      // Loopback-only (the server.ts /api gate enforces it) + origin-gated so
      // a same-machine web page can't bootstrap the token (C1). Returns the
      // token so the Tauri webview GUI can bootstrap its first write without a
      // separate IPC channel; subsequent POSTs echo it back in the header.
      if (!isAllowedAdminOrigin(headers["origin"])) {
        return { status: 403, body: { error: "forbidden_origin" } };
      }
      return { status: 200, body: { token: deps.adminToken ?? null } };
    }
    default:
      // Don't echo the raw pathname back — the GUI may render this string and
      // an attacker controlling the URL (e.g. via a crafted link) could inject
      // markup. The error code alone is enough for the client to branch on.
      return { status: 404, body: { error: "unknown_admin_endpoint" } };
  }
}

/**
 * POST /api/active — switch the active model/provider lock at runtime.
 * Token-gated; on success the daemon has already hot-reloaded config so the
 * next request is routed by the new lock.
 */
function handleSetActive(
  headers: Record<string, string | undefined>,
  body: string | undefined,
  deps: AdminDeps,
): AdminResponse {
  if (!deps.adminToken) return { status: 501, body: { error: "admin_disabled" } };
  if (!adminTokenOk(headers["x-agentfare-admin-token"], deps.adminToken)) {
    return { status: 401, body: { error: "invalid_admin_token" } };
  }
  if (!deps.applyLock) return { status: 503, body: { error: "reload_unavailable" } };

  let payload: any;
  try {
    payload = body ? JSON.parse(body) : {};
  } catch {
    return { status: 400, body: { error: "invalid_json" } };
  }

  const lockMode = payload?.lockMode;
  if (!VALID_LOCK_MODES.has(lockMode)) {
    return { status: 400, body: { error: "invalid_lock_mode", valid: [...VALID_LOCK_MODES] } };
  }
  const activeModel = typeof payload?.activeModel === "string" ? payload.activeModel : undefined;
  const activeProvider = typeof payload?.activeProvider === "string" ? payload.activeProvider : undefined;
  if (lockMode === "model" && !activeModel) {
    return { status: 400, body: { error: "active_model_required" } };
  }
  if (lockMode === "provider" && !activeProvider) {
    return { status: 400, body: { error: "active_provider_required" } };
  }

  const result = deps.applyLock({ lockMode, activeModel, activeProvider });
  if (!result.ok) return { status: 400, body: { error: result.error } };
  return {
    status: 200,
    body: { ok: true, lockMode, activeModel: activeModel ?? null, activeProvider: activeProvider ?? null },
  };
}

/**
 * POST /api/keys — persist API keys to keys.json（GUI Settings 填 key，A2）。
 * Token-gated; saveKeys 原子合并 + 权限加固 + 失效缓存，下一个请求即按新
 * key 转发，无需 reload。响应只回显已写入的 provider 名列表——绝不回显
 * key 值（admin.ts 契约：不回显用户控制输入，防注入/泄露）。
 */
function handleSetKeys(
  headers: Record<string, string | undefined>,
  body: string | undefined,
  deps: AdminDeps,
): AdminResponse {
  if (!deps.adminToken) return { status: 501, body: { error: "admin_disabled" } };
  if (!adminTokenOk(headers["x-agentfare-admin-token"], deps.adminToken)) {
    return { status: 401, body: { error: "invalid_admin_token" } };
  }
  if (!deps.saveKeys) return { status: 503, body: { error: "key_store_unavailable" } };

  let payload: any;
  try {
    payload = body ? JSON.parse(body) : {};
  } catch {
    return { status: 400, body: { error: "invalid_json" } };
  }

  // 必须是扁平 Record<string,string>：provider 名 + key 值均非空字符串。
  // keys.json 是 provider→key 映射，不接受数组/原始值/嵌套对象。
  if (typeof payload !== "object" || payload === null || Array.isArray(payload)) {
    return { status: 400, body: { error: "invalid_keys_shape" } };
  }
  const updates: Record<string, string> = {};
  for (const [provider, key] of Object.entries(payload)) {
    if (typeof provider !== "string" || provider === "" || typeof key !== "string" || key === "") {
      return { status: 400, body: { error: "invalid_key_entry" } };
    }
    updates[provider] = key;
  }
  if (Object.keys(updates).length === 0) {
    return { status: 400, body: { error: "no_keys_provided" } };
  }

  deps.saveKeys(updates);
  return { status: 200, body: { ok: true, providers: Object.keys(updates) } };
}

/**
 * POST /api/providers — merge provider config（baseUrl/upstreamUrl）进
 * config.json 并热加载（GUI Settings 加/改 provider，如指向中转站，A3）。
 * Token-gated; applyProviders 经 buildProvidersConfigJson patch（保留其余字段）
 * → 原子写 → reloadConfig 重建 providerMap。
 */
/** 校验 http/https URL 形态——纯 GUI 用户拼错的 baseUrl/upstreamUrl 不应静默落盘触发隐蔽路由失败。 */
function isValidHttpUrl(s: string): boolean {
  try {
    const u = new URL(s);
    return u.protocol === "http:" || u.protocol === "https:";
  } catch {
    return false;
  }
}

function handleSetProviders(
  headers: Record<string, string | undefined>,
  body: string | undefined,
  deps: AdminDeps,
): AdminResponse {
  if (!deps.adminToken) return { status: 501, body: { error: "admin_disabled" } };
  if (!adminTokenOk(headers["x-agentfare-admin-token"], deps.adminToken)) {
    return { status: 401, body: { error: "invalid_admin_token" } };
  }
  if (!deps.applyProviders) return { status: 503, body: { error: "reload_unavailable" } };

  let payload: any;
  try {
    payload = body ? JSON.parse(body) : {};
  } catch {
    return { status: 400, body: { error: "invalid_json" } };
  }

  // 必须是 Record<string, ProviderConfig>：每个 provider 有非空 baseUrl
  // （路由必需），upstreamUrl 可选非空字符串。校验错误只回显 code，不回显
  // provider 名（用户可经对照自己提交的 payload 定位）。
  if (typeof payload !== "object" || payload === null || Array.isArray(payload)) {
    return { status: 400, body: { error: "invalid_providers_shape" } };
  }
  const update: Record<string, ProviderConfig> = {};
  for (const [name, cfg] of Object.entries(payload)) {
    if (typeof name !== "string" || name === "") {
      return { status: 400, body: { error: "invalid_provider_name" } };
    }
    if (typeof cfg !== "object" || cfg === null || Array.isArray(cfg)) {
      return { status: 400, body: { error: "invalid_provider_config" } };
    }
    const c = cfg as { baseUrl?: unknown; upstreamUrl?: unknown };
    if (typeof c.baseUrl !== "string" || c.baseUrl === "") {
      return { status: 400, body: { error: "base_url_required" } };
    }
    if (!isValidHttpUrl(c.baseUrl)) {
      return { status: 400, body: { error: "invalid_base_url" } };
    }
    if (c.upstreamUrl !== undefined && (typeof c.upstreamUrl !== "string" || c.upstreamUrl === "")) {
      return { status: 400, body: { error: "invalid_upstream_url" } };
    }
    if (c.upstreamUrl !== undefined && !isValidHttpUrl(c.upstreamUrl)) {
      return { status: 400, body: { error: "invalid_upstream_url" } };
    }
    update[name] =
      c.upstreamUrl !== undefined ? { baseUrl: c.baseUrl, upstreamUrl: c.upstreamUrl } : { baseUrl: c.baseUrl };
  }
  if (Object.keys(update).length === 0) {
    return { status: 400, body: { error: "no_providers_provided" } };
  }

  const result = deps.applyProviders(update);
  if (!result.ok) return { status: 400, body: { error: result.error } };
  return { status: 200, body: { ok: true, providers: Object.keys(update) } };
}
