/**
 * @agentfare/proxy — Admin API (loopback-only).
 *
 * JSON endpoints the GUI (and any local tooling) use to inspect cost data, logs,
 * the model registry, the provider map, and — since the cc-switch rework — to
 * read/switch the active model lock at runtime.
 *
 * Security: read endpoints carry no auth of their own; the HTTP layer in
 * server.ts gates the whole /api branch on a loopback remote address as
 * defense-in-depth. Write endpoints (POST /api/active) additionally require an
 * admin token (x-agentfare-admin-token header) generated by the daemon at
 * startup and persisted to proxy.json — the token scheme this file originally
 * reserved. The token bootstrap (GET /api/admin-token) and the write endpoint
 * are further origin-gated (isAllowedAdminOrigin): a same-machine web page has
 * a loopback source IP, so loopback alone can't stop it — browsers always
 * send Origin, which must be the Tauri webview or vite dev origin (or absent
 * for curl/SDK). This is not a multi-user boundary (any process that can read
 * keys.json can already impersonate the user), but it satisfies the explicit
 * "do not add write endpoints without a token scheme" contract and guards
 * against accidental/drive-by POSTs and same-machine web-origin attacks.
 */

import * as crypto from "node:crypto";
import type { TrackingDatabase, RoutingConfig } from "@agentfare/core";
import type { ModelRegistry } from "@agentfare/models";
import type { ProviderInfo } from "./provider-map.js";

/** cc-switch 手动锁定请求/响应体。 */
export interface ActiveLock {
  lockMode: "auto" | "model" | "provider";
  activeModel?: string;
  activeProvider?: string;
}

export interface AdminDeps {
  db?: TrackingDatabase;
  registry?: ModelRegistry;
  providerMap?: Record<string, ProviderInfo>;
  /** 当前 routing 配置（GET /api/active 读锁定状态）。 */
  getRouting?: () => RoutingConfig;
  /**
   * 应用手动锁定并热加载配置（POST /api/active）。daemon 端实现：写
   * config.json 的 routing.lockMode/activeModel/activeProvider → 重建
   * RequestHandler/ModelRegistry/providerMap，使下一个请求即按新锁定路由。
   */
  applyLock?: (lock: ActiveLock) => { ok: true } | { ok: false; error: string };
  /** admin 写端点鉴权 token；未配置则写端点拒绝（501 admin_disabled）。 */
  adminToken?: string;
}

export interface AdminResponse {
  status: number;
  body: unknown;
}

const RANGE_RE = /^(\d+)([dhm])$/;
const DEFAULT_LOG_LIMIT = 100;
const MAX_LOG_LIMIT = 1000;
const VALID_LOCK_MODES: ReadonlySet<string> = new Set(["auto", "model", "provider"]);

/**
 * Parse a time range (e.g. "7d", "24h", "30m"). Invalid input is ignored
 * (treated as "all-time") rather than rejected — the GUI may forward
 * user-typed values, and the read path fails soft.
 */
function parseRange(range: string | undefined): string | undefined {
  if (!range) return undefined;
  return RANGE_RE.test(range) ? range : undefined;
}

function parseLimit(raw: string | undefined): number {
  const n = parseInt(raw ?? "", 10);
  if (!Number.isFinite(n) || n <= 0) return DEFAULT_LOG_LIMIT;
  return Math.min(n, MAX_LOG_LIMIT);
}

/**
 * Constant-time admin-token check. Both sides are SHA-256 hashed to a fixed
 * length before timingSafeEqual, so a length mismatch no longer
 * short-circuits — short-circuiting on length would leak len(expected) as a
 * timing oracle if tokens were ever variable-length (today's randomUUID is a
 * fixed 36 chars, but the hash makes the constant-time contract hold
 * regardless). Returns false if either side is missing.
 */
function adminTokenOk(provided: string | undefined, expected: string | undefined): boolean {
  if (!expected || !provided) return false;
  const a = crypto.createHash("sha256").update(provided).digest();
  const b = crypto.createHash("sha256").update(expected).digest();
  return crypto.timingSafeEqual(a, b);
}

/**
 * Origins allowed to read the admin token / call the write endpoint. The GUI
 * ships as a Tauri webview (`tauri://localhost` on macOS/Linux,
 * `http://tauri.localhost` on Windows WebView2); vite dev runs on
 * `http://localhost:5173` (and `http://127.0.0.1:5173`). A loopback remote
 * address alone is NOT sufficient: any web page the user opens in a browser
 * on the same machine also has a loopback source IP, so without an origin
 * gate a malicious site could GET /api/admin-token (a simple request — no
 * preflight, and an echoing ACAO would let its JS read the response) then
 * POST /api/active to silently re-route all the user's LLM traffic.
 */
const ADMIN_ALLOWED_ORIGINS: ReadonlySet<string> = new Set([
  "tauri://localhost",
  "http://tauri.localhost",
  "http://localhost:5173",
  "http://127.0.0.1:5173",
]);

/**
 * Whether a request's Origin may read the admin token / call the write
 * endpoint. An absent Origin (curl/SDK) is allowed — those callers are
 * already gated by the loopback check + token; this check exists solely to
 * stop a web page (which always sends Origin on cross-site fetches) from
 * bootstrapping the token.
 */
export function isAllowedAdminOrigin(origin: string | undefined): boolean {
  if (!origin) return true;
  return ADMIN_ALLOWED_ORIGINS.has(origin);
}

/**
 * Whether a request's remote address is loopback (127.0.0.0/8 or ::1, incl.
 * IPv4-mapped ::ffff:127.x.x.x). Admin endpoints are loopback-only.
 */
export function isLoopback(addr: string | undefined): boolean {
  if (!addr) return false;
  if (addr === "::1") return true;
  if (addr.startsWith("::ffff:")) {
    const v4 = addr.slice(7);
    return v4.startsWith("127.");
  }
  return /^127\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(addr);
}

/**
 * Dispatch a /api/* admin request. Returns null when the path is not under
 * /api, so the caller can fall through to normal proxy routing.
 */
export function handleAdminRequest(
  method: string,
  pathname: string,
  query: Record<string, string | undefined>,
  headers: Record<string, string | undefined>,
  body: string | undefined,
  deps: AdminDeps,
): AdminResponse | null {
  if (!pathname.startsWith("/api")) return null;

  // Write endpoint (POST, token-gated). Origin is checked before the token so
  // a non-allowlisted web page never learns whether its token guess was right.
  if (method === "POST" && pathname === "/api/active") {
    if (!isAllowedAdminOrigin(headers["origin"])) {
      return { status: 403, body: { error: "forbidden_origin" } };
    }
    return handleSetActive(headers, body, deps);
  }

  // All other admin endpoints are read-only GET
  if (method !== "GET") return { status: 405, body: { error: "method_not_allowed" } };

  switch (pathname) {
    case "/api/cost": {
      if (!deps.db) return { status: 503, body: { error: "db_unavailable" } };
      const range = parseRange(query.range);
      return {
        status: 200,
        body: {
          summary: deps.db.getCostSummary(range),
          byStep: deps.db.getStepSummary(range),
          byTool: deps.db.getToolSummary(range),
        },
      };
    }
    case "/api/logs": {
      if (!deps.db) return { status: 503, body: { error: "db_unavailable" } };
      const limit = parseLimit(query.limit);
      const logs = deps.db.queryLogs({}, limit);
      return { status: 200, body: { logs } };
    }
    case "/api/models": {
      if (!deps.registry) return { status: 503, body: { error: "registry_unavailable" } };
      const models = deps.registry.getAll().map((m) => ({
        id: m.id,
        provider: m.provider,
        tier: m.tier,
        pricing: {
          inputPerMillion: m.pricing.inputPerMillion,
          outputPerMillion: m.pricing.outputPerMillion,
        },
      }));
      return { status: 200, body: { models } };
    }
    case "/api/scores": {
      if (!deps.db) return { status: 503, body: { error: "db_unavailable" } };
      return { status: 200, body: { scores: deps.db.loadAllModelScores() } };
    }
    case "/api/providers": {
      return { status: 200, body: { providers: deps.providerMap ?? {} } };
    }
    case "/api/active": {
      const routing = deps.getRouting?.();
      return {
        status: 200,
        body: {
          lockMode: routing?.lockMode ?? "auto",
          activeModel: routing?.activeModel ?? null,
          activeProvider: routing?.activeProvider ?? null,
        },
      };
    }
    case "/api/admin-token": {
      // Loopback-only (the server.ts /api gate enforces it) + origin-gated so
      // a same-machine web page can't bootstrap the token (C1). Returns the
      // token so the Tauri webview GUI can bootstrap its first write without a
      // separate IPC channel; subsequent POSTs echo it back in the header.
      if (!isAllowedAdminOrigin(headers["origin"])) {
        return { status: 403, body: { error: "forbidden_origin" } };
      }
      return { status: 200, body: { token: deps.adminToken ?? null } };
    }
    default:
      // Don't echo the raw pathname back — the GUI may render this string and
      // an attacker controlling the URL (e.g. via a crafted link) could inject
      // markup. The error code alone is enough for the client to branch on.
      return { status: 404, body: { error: "unknown_admin_endpoint" } };
  }
}

/**
 * POST /api/active — switch the active model/provider lock at runtime.
 * Token-gated; on success the daemon has already hot-reloaded config so the
 * next request is routed by the new lock.
 */
function handleSetActive(
  headers: Record<string, string | undefined>,
  body: string | undefined,
  deps: AdminDeps,
): AdminResponse {
  if (!deps.adminToken) return { status: 501, body: { error: "admin_disabled" } };
  if (!adminTokenOk(headers["x-agentfare-admin-token"], deps.adminToken)) {
    return { status: 401, body: { error: "invalid_admin_token" } };
  }
  if (!deps.applyLock) return { status: 503, body: { error: "reload_unavailable" } };

  let payload: any;
  try {
    payload = body ? JSON.parse(body) : {};
  } catch {
    return { status: 400, body: { error: "invalid_json" } };
  }

  const lockMode = payload?.lockMode;
  if (!VALID_LOCK_MODES.has(lockMode)) {
    return { status: 400, body: { error: "invalid_lock_mode", valid: [...VALID_LOCK_MODES] } };
  }
  const activeModel = typeof payload?.activeModel === "string" ? payload.activeModel : undefined;
  const activeProvider = typeof payload?.activeProvider === "string" ? payload.activeProvider : undefined;
  if (lockMode === "model" && !activeModel) {
    return { status: 400, body: { error: "active_model_required" } };
  }
  if (lockMode === "provider" && !activeProvider) {
    return { status: 400, body: { error: "active_provider_required" } };
  }

  const result = deps.applyLock({ lockMode, activeModel, activeProvider });
  if (!result.ok) return { status: 400, body: { error: result.error } };
  return {
    status: 200,
    body: { ok: true, lockMode, activeModel: activeModel ?? null, activeProvider: activeProvider ?? null },
  };
}
