/**
 * HTTP proxy server for AgentFare.
 *
 * Accepts LLM API requests from any tool via *_BASE_URL environment variables,
 * runs routing analysis, optionally converts protocol, forwards to the real
 * provider, and streams the response back while extracting token usage for
 * cost tracking.
 */

import * as nodeHttps from "node:https";
import * as nodeHttp from "node:http";
import { URL } from "node:url";
import { resolveProvider, getUpstreamPath, buildVirtualUrl, type ProviderInfo } from "./provider-map.js";
import { resolveApiKey, buildAuthHeaders } from "./key-store.js";
import { SSEPipe, type StreamTokenData } from "./sse-pipe.js";
import type { RequestHandler, HandleResult } from "@agentfare/hook/request-handler";
import {
  resolveEffectiveBaseUrl,
  detectKeyHostConflict,
  type CostTracker,
  type QualitySignalCollector,
  type TrackingDatabase,
  type ProviderConfig,
} from "@agentfare/core";
import { type ModelRegistry, type ModelEntry, findEndpointForProtocol, resolveAuthScheme } from "@agentfare/models";
import {
  ANALYZER_TIMEOUT_MS,
  PASS_THROUGH_ANALYSIS,
  lookupModelEntry,
  createPassThroughModelEntry,
  detectProtocol,
  createSSEConverterForDirection,
  convertRequestBody,
  sanitizeDecisionForCallback,
  asyncLogError,
  generatePassThroughId,
} from "@agentfare/hook/pipeline";
import { CircuitBreaker, shouldFailover, hostOf } from "@agentfare/hook/failover";
import type { SSEProtocolConverter } from "@agentfare/hook/response-handler";
import { handleAdminRequest, isLoopback, isAllowedAdminOrigin, type AdminResponse, type ActiveLock } from "./admin.js";

export interface ProxyServerDeps {
  handler: RequestHandler;
  costTracker?: CostTracker;
  qualitySignalCollector?: QualitySignalCollector;
  onlineLearner?: any;
  registry?: ModelRegistry;
  /** Dynamic provider map (built from config). Falls back to DEFAULT if not provided. */
  providerMap?: Record<string, ProviderInfo>;
  /**
   * TrackingDatabase for the admin API (/api/*). Optional — admin endpoints
   * that need it return 503 when absent. The daemon passes the same instance
   * used by costTracker (no second connection to the SQLite file).
   */
  db?: TrackingDatabase;
  /** 当前 routing 配置，供 GET /api/active 读锁定状态。 */
  getRouting?: () => import("@agentfare/core").RoutingConfig;
  /** 应用手动锁定 + 热加载配置，供 POST /api/active。 */
  applyLock?: (lock: ActiveLock) => { ok: true } | { ok: false; error: string };
  /** 持久化 API key 到 keys.json，供 POST /api/keys（GUI 一等公民 A2）。 */
  saveKeys?: (updates: Record<string, string>) => void;
  /** 合并 provider 配置进 config.json 并热加载，供 POST /api/providers（A3）。 */
  applyProviders?: (
    update: Record<string, ProviderConfig>,
  ) => { ok: true } | { ok: false; error: string };
}

export interface ProxyServerOptions {
  port: number;
  deps: ProxyServerDeps;
  /**
   * Admin token gating write endpoints (POST /api/active). Generated by the
   * daemon at startup and persisted to proxy.json; the GUI bootstraps it via
   * GET /api/admin-token (loopback-only). Optional — when absent, write
   * endpoints return 501 admin_disabled.
   */
  adminToken?: string;
  /** Called when a routing decision is made (for logging/telemetry) */
  onRouting?: (result: HandleResult) => void;
  /** Called on unhandled errors */
  onError?: (err: unknown) => void;
  /**
   * Override upstream URL resolution for testing.
   * Receives the computed target URL, returns the actual URL to forward to.
   * If not provided, uses the target URL as-is.
   */
  resolveUpstream?: (targetUrl: string) => string;
}

const UPSTREAM_TIMEOUT_MS = 120_000;

/**
 * Cap request body size to bound memory use under adversarial input; real LLM
 * requests are far under this.
 */
const MAX_REQUEST_BODY_BYTES = 100 * 1024 * 1024; // 100 MB

/**
 * Hop-by-hop headers (RFC 7230 §6.1) must not be forwarded by a proxy, plus
 * content-length which we recompute (streaming → chunked; a protocol-converted
 * body has a different length) rather than trusting the upstream's value —
 * forwarding a stale content-length truncates or pads the client's read.
 */
const HOP_BY_HOP_RESPONSE_HEADERS = new Set([
  "connection", "keep-alive", "proxy-authenticate", "proxy-authorization",
  "te", "trailers", "transfer-encoding", "upgrade", "content-length",
]);

/**
 * CORS headers for the read-only admin + health endpoints.
 *
 * The production GUI ships as a Tauri webview whose origin is
 * `tauri://localhost` (macOS/Linux) or `http://tauri.localhost` (Windows
 * WebView2) — a different origin from the loopback daemon at 127.0.0.1:3456.
 * Without `Access-Control-Allow-Origin` the webview blocks JS from reading the
 * response and the GUI renders permanently offline. Allowing any origin is
 * safe: these endpoints are loopback-only (the socket-level `isLoopback` gate
 * in the /api branch is the real auth boundary) and strictly read-only GET, so
 * CORS is only a browser-read gate layered on top. The proxy POST path
 * (upstream LLM calls) intentionally does NOT send these — it is consumed by
 * SDK clients, not browsers.
 */
const READ_ENDPOINT_CORS_HEADERS: Record<string, string> = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET, OPTIONS",
  "access-control-allow-headers": "Content-Type",
  "access-control-max-age": "86400",
};

/**
 * Admin POST bodies are a small JSON lock payload ({lockMode, activeModel,
 * activeProvider}); cap far below the 100 MB LLM-request limit so a holder of
 * the token (or a web page that stole it via the admin-token bootstrap) can't
 * amplify memory use with oversized POSTs.
 */
const MAX_ADMIN_BODY_BYTES = 8 * 1024; // 8 KB

/**
 * Build admin CORS headers for a given request Origin. Only a present,
 * allowlisted Origin (the Tauri webview + vite dev, via isAllowedAdminOrigin)
 * gets an echoing Access-Control-Allow-Origin; any other Origin — including an
 * arbitrary web page reaching the loopback port from the same machine — gets
 * NO ACAO, so the browser blocks its JS from reading the response. This closes
 * C1: with a bare ACAO:* the simple GET /api/admin-token (no preflight) handed
 * the token to any same-machine website, which could then POST /api/active to
 * re-route all traffic. An absent Origin (curl/SDK) also gets no ACAO —
 * non-browser callers don't enforce CORS, and are already gated by loopback +
 * token.
 */
function buildAdminCorsHeaders(origin: string | undefined): Record<string, string> {
  const headers: Record<string, string> = {
    "access-control-allow-methods": "GET, POST, OPTIONS",
    "access-control-allow-headers": "Content-Type, x-agentfare-admin-token",
    "access-control-max-age": "86400",
    // Vary by Origin so a shared cache doesn't serve an allowlisted ACAO to a
    // denied origin (or vice versa).
    "vary": "origin",
  };
  if (origin && isAllowedAdminOrigin(origin)) {
    headers["access-control-allow-origin"] = origin;
  }
  return headers;
}

/**
 * CORS headers for /api OPTIONS preflights. A preflight carries no credentials
 * and never returns the admin token, so ACAO:* is safe here — the security
 * boundary is the *actual* response ({@link adminResponseCors}) plus the origin
 * gate + token check inside handleAdminRequest. Allows the full method set so a
 * POST /api/active preflight from the GUI passes without a per-path lookup.
 */
const PREFLIGHT_CORS_HEADERS: Record<string, string> = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET, POST, OPTIONS",
  "access-control-allow-headers": "Content-Type, x-agentfare-admin-token",
  "access-control-max-age": "86400",
};

/**
 * Pick CORS headers for an *actual* admin response (not a preflight). Sensitive
 * endpoints — POST /api/active (mutates routing) and GET /api/admin-token
 * (returns the token) — echo ACAO only for an allowlisted Origin (C1: a bare
 * ACAO:* let any same-machine website read the token then POST /api/active to
 * re-route all traffic). Read endpoints (/api/cost, /api/providers, GET
 * /api/active status) keep ACAO:* — they carry no secret and are already
 * loopback-gated, so ACAO:* only widens browser-read, not auth.
 */
function adminResponseCors(
  method: string,
  pathname: string,
  origin: string | undefined,
): Record<string, string> {
  const sensitive =
    (method === "POST" &&
      (pathname === "/api/active" || pathname === "/api/keys" || pathname === "/api/providers")) ||
    (method === "GET" && pathname === "/api/admin-token");
  return sensitive ? buildAdminCorsHeaders(origin) : READ_ENDPOINT_CORS_HEADERS;
}

/**
 * Per-host circuit breaker for upstream providers. Module-level singleton so a
 * tripped host is short-circuited for the lifetime of the daemon process.
 */
const upstreamCircuit = new CircuitBreaker();

/**
 * Create and return the proxy HTTP server (not yet listening).
 */
export function createProxyServer(options: ProxyServerOptions): nodeHttp.Server {
  const { deps, onRouting, onError } = options;

  const server = nodeHttp.createServer(async (req, res) => {
    try {
      await handleRequest(req, res, options);
    } catch (err) {
      asyncLogError(err, "proxy");
      onError?.(err);
      if (!res.headersSent) {
        res.writeHead(502, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "proxy_error", message: String(err) }));
      } else {
        // Headers already sent (mid-stream): can't emit a JSON error, so tear
        // the connection down — otherwise the client hangs waiting for bytes.
        res.destroy();
      }
    }
  });

  server.timeout = UPSTREAM_TIMEOUT_MS;
  server.keepAliveTimeout = 60_000;

  return server;
}

/**
 * Core request handler for every incoming request.
 */
async function handleRequest(
  req: nodeHttp.IncomingMessage,
  res: nodeHttp.ServerResponse,
  options: ProxyServerOptions,
): Promise<void> {
  const requestPath = req.url ?? "/";

  // Health check
  if (requestPath === "/health" || requestPath === "/") {
    if (req.method === "OPTIONS") {
      res.writeHead(204, READ_ENDPOINT_CORS_HEADERS);
      res.end();
      return;
    }
    res.writeHead(200, { "Content-Type": "application/json", ...READ_ENDPOINT_CORS_HEADERS });
    res.end(JSON.stringify({ status: "ok", service: "agentfare-proxy" }));
    return;
  }

  // Admin API (loopback-only). Must be handled before resolveProvider, which
  // would 404 any non-provider path as "unknown_provider". The GUI and any
  // local tooling read cost/logs/models here; cross-network callers are
  // refused — these read endpoints otherwise carry no auth of their own.
  if (requestPath === "/api" || requestPath.startsWith("/api/")) {
    if (!isLoopback(req.socket.remoteAddress)) {
      res.writeHead(403, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: "forbidden", reason: "loopback_only" }));
      return;
    }
    // CORS preflight for the admin API. The webview GUI is a cross-origin
    // caller; answer OPTIONS before handleAdminRequest. The admin API now
    // includes POST write endpoints (POST /api/active), so the preflight allows
    // GET/POST/OPTIONS and the x-agentfare-admin-token header.
    if (req.method === "OPTIONS") {
      res.writeHead(204, PREFLIGHT_CORS_HEADERS);
      res.end();
      return;
    }
    const adminUrl = new URL(req.url ?? "/", "http://localhost");
    const query: Record<string, string | undefined> = {};
    for (const [k, v] of adminUrl.searchParams) query[k] = v;

    // Write endpoints (POST /api/active) carry a JSON body; read endpoints
    // don't. Read the body only for POST so a GET /api/cost doesn't block
    // waiting for a request body the SDK client never sends.
    let adminBody: string | undefined;
    if (req.method === "POST") {
      try {
        // Admin POST payloads are tiny lock JSON — cap at MAX_ADMIN_BODY_BYTES,
        // not the 100 MB LLM-request limit, to bound memory under adversarial input.
        adminBody = await readBody(req, MAX_ADMIN_BODY_BYTES);
      } catch {
        res.writeHead(413, { "Content-Type": "application/json", ...adminResponseCors(req.method ?? "GET", adminUrl.pathname, req.headers.origin) });
        res.end(JSON.stringify({ error: "request_body_too_large" }));
        return;
      }
    }
    const adminHeaders = extractNodeHeaders(req);

    // handleAdminRequest reads from the SQLite db / in-memory registry, or
    // mutates config via applyLock on POST /api/active. A db/disk error must
    // NOT bubble to the outer 502 catch — that path emits `message:
    // String(err)` and would leak SQL/column/path internals into the response
    // body. Isolate it and return an opaque 500 instead.
    let adminRes: AdminResponse;
    try {
      adminRes = handleAdminRequest(
        req.method ?? "GET",
        adminUrl.pathname,
        query,
        adminHeaders,
        adminBody,
        {
          db: options.deps.db,
          registry: options.deps.registry,
          providerMap: options.deps.providerMap,
          getRouting: options.deps.getRouting,
          applyLock: options.deps.applyLock,
          // GUI 一等公民 A2/A3：透传写端点回调到 handleAdminRequest。漏传任一 →
          // handler 收到 undefined → 503 key_store/reload unavailable。单元测
          // adminPost 直调 handleAdminRequest 绕过此透传，故 e2e "POST /api/keys
          // persists keys over HTTP" 是这条透传线的唯一守卫——别再漏。
          saveKeys: options.deps.saveKeys,
          applyProviders: options.deps.applyProviders,
          adminToken: options.adminToken,
        },
      ) ?? { status: 404, body: { error: "unknown_admin_endpoint" } };
    } catch (adminErr) {
      asyncLogError(`admin handler error: ${adminErr}`, "proxy");
      adminRes = { status: 500, body: { error: "admin_internal" } };
    }
    res.writeHead(adminRes.status, { "Content-Type": "application/json", ...adminResponseCors(req.method ?? "GET", adminUrl.pathname, req.headers.origin) });
    res.end(JSON.stringify(adminRes.body));
    return;
  }

  // Resolve provider from path prefix
  const providerInfo = resolveProvider(requestPath, options.deps.providerMap);
  if (!providerInfo) {
    res.writeHead(404, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "unknown_provider", path: requestPath }));
    return;
  }

  // Only handle POST requests (LLM API calls)
  if (req.method !== "POST") {
    res.writeHead(405, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "method_not_allowed" }));
    return;
  }

  // Read request body (capped to bound memory use under adversarial input)
  let bodyStr: string;
  try {
    bodyStr = await readBody(req);
  } catch {
    res.writeHead(413, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "request_body_too_large" }));
    return;
  }
  if (!bodyStr) {
    res.writeHead(400, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "empty_body" }));
    return;
  }

  // Extract headers
  const headers = extractNodeHeaders(req);

  // Build virtual URL (what the client thinks it's calling)
  const upstreamPath = getUpstreamPath(requestPath);
  const virtualUrl = buildVirtualUrl(providerInfo, upstreamPath);

  // Determine if streaming
  let body: any;
  try {
    body = JSON.parse(bodyStr);
  } catch {
    res.writeHead(400, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "invalid_json" }));
    return;
  }
  // Accept both boolean true and the string "true" — some clients send the
  // latter, and a strict === true would misroute them to the buffered path.
  const isStreaming = body.stream === true || body.stream === "true";
  const originalModel = body.model ?? "";

  // --- Quality signal: detect manual model switch ---
  if (options.deps.qualitySignalCollector && originalModel) {
    const sessionId = headers["x-request-id"] ?? headers["x-session-id"] ?? "default";
    if (options.deps.qualitySignalCollector.detectManualSwitch(sessionId, originalModel)) {
      options.deps.qualitySignalCollector.recordSignal(originalModel, "unknown", "manual_switch", sessionId);
    }
  }

  // --- Run routing analysis ---
  // Abort the analyzer on timeout so it can't keep running (holding resources)
  // after we've already given up and fallen back. The timer is cleared when the
  // analyzer wins the race so it doesn't leak across requests.
  const abortCtrl = new AbortController();
  let analysisTimer: NodeJS.Timeout | undefined;
  const result = await Promise.race([
    options.deps.handler.handle(virtualUrl, bodyStr, headers, abortCtrl.signal),
    new Promise<null>((resolve) => {
      analysisTimer = setTimeout(() => { abortCtrl.abort(); resolve(null); }, ANALYZER_TIMEOUT_MS);
    }),
  ]) as HandleResult | null;
  if (analysisTimer) clearTimeout(analysisTimer);

  // Determine target URL, body, headers, and whether protocol conversion is needed
  let targetUrl: string;
  let targetBodyStr: string;
  let targetHeaders: Record<string, string>;
  let sourceProtocol: "openai" | "anthropic" = providerInfo.protocol;
  let targetProtocol: "openai" | "anthropic" = providerInfo.protocol;
  let needsProtocolConversion = false;
  let targetProvider = providerInfo.provider;

  if (result && result.decision.targetModel) {
    const targetModel = result.decision.targetModel;
    // Pick the endpoint whose protocol matches the client's source protocol.
    // Claude Code (anthropic) → a DeepSeek/Kimi/Zhipu model hits that vendor's
    // anthropic-compatible endpoint directly, avoiding openai↔anthropic conversion.
    const targetApi = findEndpointForProtocol(targetModel, sourceProtocol);

    if (result.decision.providerSwitched) {
      // Cross-provider routing.
      // ISSUE: previously used targetApi.baseUrl (the official endpoint), ignoring
      // the user's relay upstreamUrl — relay keys hit api.anthropic.com → ban risk.
      const providerUpstreamBaseUrl = options.deps.providerMap?.[targetModel.provider]?.upstreamBaseUrl;
      const effectiveBaseUrl = resolveEffectiveBaseUrl({
        enterpriseBaseUrl: result.decision.enterpriseConfig?.baseUrl,
        providerUpstreamBaseUrl,
        targetApiBaseUrl: targetApi.baseUrl,
      });
      // Ban-guard: if a relay-configured provider would still be routed to an
      // official host (e.g. a conflicting enterprise policy overriding the
      // relay), refuse the cross-provider hop and fall back to the ORIGINAL
      // request — routing the relay key to the official endpoint risks a ban.
      // resolveEffectiveBaseUrl already prefers the relay, so conflict only
      // fires under a conflicting enterprise policy or an empty-string override.
      const hostConflict = detectKeyHostConflict({ effectiveBaseUrl, providerUpstreamBaseUrl });
      // Surface the resolved host + validation result on the decision so
      // onRouting/telemetry can audit which upstream a route actually reached.
      result.decision.effectiveBaseUrl = effectiveBaseUrl;
      result.decision.keyHostBindingValidated = !hostConflict.conflict;
      if (hostConflict.conflict) {
        asyncLogError(
          `封号风险,降级到原始请求: ${hostConflict.reason} (provider=${targetModel.provider})`,
          "proxy",
        );
        // Abort cross-provider routing: keep the original URL/body/headers so
        // the request reaches the client's configured provider, not the vendor.
        targetUrl = virtualUrl;
        targetBodyStr = result.modifiedBody;
        targetHeaders = { ...headers };
        // targetProtocol / needsProtocolConversion stay at same-provider defaults
      } else {
        targetUrl = targetApi.protocol === "anthropic"
          ? `${effectiveBaseUrl}/v1/messages`
          : `${effectiveBaseUrl}/chat/completions`;
        targetProtocol = targetApi.protocol;
        needsProtocolConversion = sourceProtocol !== targetProtocol;
        targetProvider = targetModel.provider;

        // Resolve API key for target provider
        const apiKey = result.decision.apiKey ?? resolveApiKey(targetModel.provider, headers);
        if (apiKey) {
          targetHeaders = { ...headers, ...buildAuthHeaders(targetModel.provider, apiKey, resolveAuthScheme(targetApi)) };
          // Remove conflicting auth headers
          if (targetApi.protocol === "anthropic") {
            delete targetHeaders["Authorization"];
          } else {
            delete targetHeaders["x-api-key"];
          }
        } else {
          targetHeaders = { ...headers };
        }

        // Convert request body if protocol changes (using shared pipeline)
        if (needsProtocolConversion) {
          targetBodyStr = convertRequestBody(sourceProtocol, targetProtocol, result.modifiedBody, targetApi.modelId);
        } else {
          targetBodyStr = result.modifiedBody;
        }
      }
    } else {
      // Same-provider routing: just change the model in the body
      targetUrl = virtualUrl;
      targetBodyStr = result.modifiedBody;
      targetHeaders = { ...headers };
    }
  } else {
    // No routing change — pass through to original provider
    targetUrl = virtualUrl;
    targetBodyStr = bodyStr;
    targetHeaders = { ...headers };

    // Resolve API key for original provider if not in headers
    if (!resolveApiKey(providerInfo.provider, targetHeaders)) {
      const key = resolveApiKey(providerInfo.provider, headers);
      if (key) {
        targetHeaders = { ...targetHeaders, ...buildAuthHeaders(providerInfo.provider, key, resolveAuthScheme({ protocol: providerInfo.protocol })) };
      }
    }
  }

  // --- Strip proxy-specific internal headers ---
  delete targetHeaders["host"];
  delete targetHeaders["content-length"];

  // --- Forward to upstream (circuit breaker + failover) ---
  // ISSUE: previously only HTTP >= 500 triggered a single fallback; 429/408/
  // timeouts and network errors were uncaught (forwardRequest rejected → 502),
  // and there was no circuit breaker so a downed host was retried every request.
  const targetHost = hostOf(targetUrl);
  let upstreamRes: nodeHttp.IncomingMessage | undefined;
  let forwardError: unknown;
  if (upstreamCircuit.allowRequest(targetHost)) {
    upstreamCircuit.onAttempt(targetHost);
    try {
      upstreamRes = await forwardRequest(targetUrl, targetBodyStr, targetHeaders, options.resolveUpstream);
    } catch (err) {
      forwardError = err; // network error / timeout — previously a bare 502
    }
  } else {
    asyncLogError(`熔断器开启: 跳过 ${targetHost}`, "proxy");
  }

  // --- Failover: 5xx / 429 / 408 / network error / timeout → fall back to original ---
  if (shouldFailover(upstreamRes?.statusCode, forwardError)) {
    if (result?.decision.targetModel) {
      asyncLogError(
        `目标模型 ${result.decision.targetModel.id} 失败 (${forwardError ? "网络错误/超时" : `状态 ${upstreamRes?.statusCode}`})`,
        "proxy",
      );
      if (options.deps.qualitySignalCollector) {
        options.deps.qualitySignalCollector.recordSignal(
          result.decision.targetModel.id,
          result.analysis.stepType,
          "error",
          result.sessionId,
        );
      }
    }
    if (upstreamRes) upstreamRes.resume(); // drain the failed response
    upstreamCircuit.recordFailure(targetHost);
    // Fallback to the original (un-routed) request. If the fallback itself
    // fails, return a structured error instead of leaking internals via 502 +
    // String(err) (which could expose upstream URLs / stack traces).
    let fallbackRes: nodeHttp.IncomingMessage;
    try {
      fallbackRes = await forwardRequest(virtualUrl, bodyStr, headers, options.resolveUpstream);
    } catch (fallbackErr) {
      asyncLogError(`fallback 也失败: ${fallbackErr}`, "proxy");
      if (!res.headersSent) {
        res.writeHead(502, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "upstream_unavailable" }));
      } else {
        res.destroy();
      }
      return;
    }
    // Fallback reached the ORIGINAL provider (virtualUrl + bodyStr + headers),
    // so the response speaks sourceProtocol, not targetProtocol. Passing the
    // latter made SSEPipe parse the body with the wrong protocol's tokenizer.
    pipeResponse(fallbackRes, res, sourceProtocol, isStreaming, originalModel, undefined, options, result, sourceProtocol, targetProtocol);
    return;
  }

  upstreamCircuit.recordSuccess(targetHost);

  // --- Record quality signals ---
  if (result?.decision.targetModel && options.deps.qualitySignalCollector) {
    options.deps.qualitySignalCollector.recordRoutedModel(
      result.sessionId,
      result.decision.targetModel.id,
      result.decision.targetModel.tier,
    );
    options.deps.qualitySignalCollector.recordRequest(
      result.sessionId,
      result.decision.targetModel.id,
      result.analysis.stepType,
    );
  }

  // --- Fire onRouting callback (strip sensitive fields) ---
  if (result?.decision) {
    const safeDecision = sanitizeDecisionForCallback(result.decision);
    options.onRouting?.({ ...result, decision: safeDecision } as HandleResult);
  }

  // --- Determine SSE converter for cross-provider streaming ---
  const sseConverter = (needsProtocolConversion && result?.decision.targetModel)
    ? createSSEConverterForDirection(sourceProtocol, targetProtocol, originalModel)
    : undefined;

  // --- Pipe response back to client ---
  // upstreamRes is defined on this path: shouldFailover() returned false, which
  // requires a concrete non-failover status code (undefined status → failover).
  pipeResponse(
    upstreamRes!, res,
    targetProtocol, isStreaming,
    originalModel,
    sseConverter,
    options,
    result,
    sourceProtocol,
    targetProtocol,
  );
}

/**
 * Pipe the upstream response to the client response,
 * optionally running through SSEPipe for token extraction.
 */
function pipeResponse(
  upstreamRes: nodeHttp.IncomingMessage,
  res: nodeHttp.ServerResponse,
  upstreamProtocol: "openai" | "anthropic",
  isStreaming: boolean,
  originalModel: string,
  sseConverter: SSEProtocolConverter | undefined,
  options: ProxyServerOptions,
  result: HandleResult | null,
  sourceProtocol?: "openai" | "anthropic",
  targetProtocol?: "openai" | "anthropic",
): void {
  // Resolve original model pricing entry for accurate cost tracking
  const originalModelEntry = options.deps.registry
    ? lookupModelEntry(options.deps.registry, originalModel)
    : undefined;

  // Forward status code and headers, stripping hop-by-hop headers and
  // content-length (see HOP_BY_HOP_RESPONSE_HEADERS). Node recomputes framing:
  // chunked for the streaming pipe, an accurate content-length for the
  // (possibly converted) buffered body.
  const statusCode = upstreamRes.statusCode ?? 200;
  const responseHeaders: Record<string, string> = {};
  for (const [key, value] of Object.entries(upstreamRes.headers)) {
    if (HOP_BY_HOP_RESPONSE_HEADERS.has(key.toLowerCase())) continue;
    if (typeof value === "string") {
      responseHeaders[key] = value;
    } else if (Array.isArray(value)) {
      responseHeaders[key] = value.join(", ");
    }
  }

  if (isStreaming) {
    // Streaming: write headers now; node uses chunked framing (omits
    // content-length automatically) since we don't set one.
    res.writeHead(statusCode, responseHeaders);
    // Use SSEPipe to extract tokens (and optionally convert protocol)
    const pipe = new SSEPipe(
      upstreamProtocol,
      (tokens: StreamTokenData) => {
        if (options.deps.costTracker && (tokens.input > 0 || tokens.output > 0)) {
          if (result) {
            options.deps.costTracker.record(
              result.analysis,
              originalModel,
              originalModelEntry,
              result.decision.targetModel!,
              result.sessionId,
              "unknown",
              tokens,
            );
          } else {
            // Pass-through: record cost for observability (no reroute)
            recordPassThroughCost(options, originalModel, tokens);
          }
        }
        if (result && options.deps.qualitySignalCollector) {
          options.deps.qualitySignalCollector.recordSignal(
            result.decision.targetModel!.id,
            result.analysis.stepType,
            "success",
            result.sessionId,
          );
        }
      },
      sseConverter,
    );
    upstreamRes.pipe(pipe).pipe(res);
  } else {
    // Non-streaming: buffer the response, optionally convert, then send
    const chunks: Buffer[] = [];
    upstreamRes.on("data", (chunk: Buffer) => chunks.push(chunk));
    upstreamRes.on("end", () => {
      let fullBody = Buffer.concat(chunks).toString("utf-8");

      // Extract tokens from non-streaming response
      try {
        const respJson = JSON.parse(fullBody);
        const tokens = upstreamProtocol === "openai"
          ? { input: respJson.usage?.prompt_tokens ?? 0, output: respJson.usage?.completion_tokens ?? 0 }
          : { input: respJson.usage?.input_tokens ?? 0, output: respJson.usage?.output_tokens ?? 0 };
        if (tokens.input > 0 || tokens.output > 0) {
          if (result) {
            options.deps.costTracker?.record(
              result.analysis,
              originalModel,
              originalModelEntry,
              result.decision.targetModel!,
              result.sessionId,
              "unknown",
              tokens,
            );
          } else {
            // Pass-through: record cost for observability (no reroute)
            recordPassThroughCost(options, originalModel, tokens);
          }
        }
      } catch (costErr) {
        process.stderr.write(`[agentfare] cost tracking error: ${costErr instanceof Error ? costErr.message : costErr}\n`);
      }

      // Non-streaming protocol conversion (ISSUE-082: previously unimplemented)
      if (sseConverter && sourceProtocol && targetProtocol && sourceProtocol !== targetProtocol) {
        try {
          const respJson = JSON.parse(fullBody);
          let converted: any;
          // Response comes FROM upstream (targetProtocol), needs converting TO client (sourceProtocol)
          if (sourceProtocol === "anthropic" && targetProtocol === "openai") {
            const { convertOpenAIToAnthropicResponse } = require("@agentfare/hook/protocol/openai-to-anthropic-response") as typeof import("@agentfare/hook/protocol/openai-to-anthropic-response");
            converted = convertOpenAIToAnthropicResponse(respJson, originalModel);
          } else if (sourceProtocol === "openai" && targetProtocol === "anthropic") {
            const { convertAnthropicToOpenAIResponse } = require("@agentfare/hook/protocol/anthropic-to-openai") as typeof import("@agentfare/hook/protocol/anthropic-to-openai");
            converted = convertAnthropicToOpenAIResponse(respJson, originalModel);
          }
          if (converted) {
            fullBody = JSON.stringify(converted);
          }
        } catch (conversionErr) {
          asyncLogError(`非流式协议转换失败: ${conversionErr}`, "proxy");
        }
      }

      // Non-streaming: the body is fully buffered, so send an accurate
      // content-length (recomputed from the final, possibly-converted body)
      // instead of letting node fall back to chunked framing.
      res.writeHead(statusCode, {
        ...responseHeaders,
        "content-length": Buffer.byteLength(fullBody).toString(),
      });
      res.end(fullBody);
    });
  }
}

/**
 * Forward a request to the upstream provider.
 */
function forwardRequest(
  targetUrl: string,
  body: string,
  headers: Record<string, string>,
  resolveUpstream?: (url: string) => string,
): Promise<nodeHttp.IncomingMessage> {
  return new Promise((resolve, reject) => {
    const effectiveUrl = resolveUpstream ? resolveUpstream(targetUrl) : targetUrl;
    const parsed = new URL(effectiveUrl);
    const isHttps = parsed.protocol === "https:";
    const lib = isHttps ? nodeHttps : nodeHttp;

    const options: nodeHttp.RequestOptions = {
      hostname: parsed.hostname,
      port: parseInt(parsed.port, 10) || (isHttps ? 443 : 80),
      path: parsed.pathname + parsed.search,
      method: "POST",
      headers: {
        ...headers,
        "content-type": "application/json",
        "content-length": Buffer.byteLength(body).toString(),
      },
    };

    const upstreamReq = lib.request(options, (upstreamRes) => {
      resolve(upstreamRes);
    });

    upstreamReq.setTimeout(UPSTREAM_TIMEOUT_MS, () => {
      upstreamReq.destroy(new Error("UPSTREAM_TIMEOUT"));
    });

    upstreamReq.on("error", (err) => {
      if (err.message === "UPSTREAM_TIMEOUT") {
        reject(new Error(`Upstream request timed out after ${UPSTREAM_TIMEOUT_MS}ms`));
      } else {
        reject(err);
      }
    });
    upstreamReq.write(body);
    upstreamReq.end();
  });
}

/**
 * Read the entire request body from an IncomingMessage.
 */
function readBody(req: nodeHttp.IncomingMessage, maxBytes: number = MAX_REQUEST_BODY_BYTES): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let size = 0;
    let aborted = false;
    req.on("data", (chunk: Buffer) => {
      if (aborted) return;
      size += chunk.length;
      if (size > maxBytes) {
        // Stop buffering an unbounded body and reject so the caller can answer
        // 413. Do NOT req.destroy() — that tears down the shared socket and the
        // 413 response then fails to write (the client sees a reset, not 413).
        // Keep draining remaining chunks (aborted → early return above) so the
        // body doesn't sit in the kernel buffer stalling the response.
        aborted = true;
        reject(new Error("request_body_too_large"));
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      if (!aborted) resolve(Buffer.concat(chunks).toString("utf-8"));
    });
    req.on("error", reject);
  });
}

/**
 * Extract headers from an IncomingMessage into a plain object.
 */
function extractNodeHeaders(req: nodeHttp.IncomingMessage): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, value] of Object.entries(req.headers)) {
    if (typeof value === "string") {
      result[key] = value;
    } else if (Array.isArray(value)) {
      result[key] = value.join(", ");
    }
  }
  return result;
}

/**
 * Record cost for pass-through requests (no model reroute).
 * Uses the registry to look up real pricing for accurate cost tracking.
 */
function recordPassThroughCost(
  options: ProxyServerOptions,
  originalModel: string,
  tokens: { input: number; output: number },
): void {
  if (!options.deps.costTracker) return;

  const registry = options.deps.registry;
  const modelEntry = registry ? lookupModelEntry(registry, originalModel) : undefined;
  const targetEntry = modelEntry ?? createPassThroughModelEntry(originalModel);

  if (!modelEntry) {
    console.warn(`[agentfare] pass-through cost tracking: model "${originalModel}" not in registry, pricing unavailable`);
  }

  options.deps.costTracker.record(
    PASS_THROUGH_ANALYSIS,
    originalModel,
    modelEntry,
    targetEntry,
    generatePassThroughId(),
    "unknown",
    tokens,
  );
}
